# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

from google.apps import chat_v1 as google_chat

chat_client = google_chat.ChatServiceClient(
    client_options={"scopes": "https://www.googleapis.com/auth/chat.bot"}
)


def retrieve_dialog_response(notes, blogs, channels, repos):
    return {
        "action": {
            "navigations": [
                {
                    "pushCard": {
                        "sections": [
                            {
                                "widgets": [
                                    {
                                        "selectionInput": {
                                            "name": "contactType",
                                            "label": "Product",
                                            "multiSelectMaxSelectedItems": "300",
                                            "multiSelectMinQueryLength": "0",
                                            "type": "MULTI_SELECT",
                                            "items": notes,
                                        }
                                    },
                                    {
                                        "selectionInput": {
                                            "name": "blogType",
                                            "label": "Blog Category",
                                            "multiSelectMaxSelectedItems": "300",
                                            "multiSelectMinQueryLength": "0",
                                            "type": "MULTI_SELECT",
                                            "items": blogs,
                                        }
                                    },
                                    {
                                        "selectionInput": {
                                            "name": "youtubeChannelType",
                                            "label": "Youtube Channel",
                                            "multiSelectMaxSelectedItems": "300",
                                            "multiSelectMinQueryLength": "0",
                                            "type": "MULTI_SELECT",
                                            "items": channels,
                                        }
                                    },
                                    {
                                        "selectionInput": {
                                            "name": "repoType",
                                            "label": "Github Repo",
                                            "multiSelectMaxSelectedItems": "300",
                                            "multiSelectMinQueryLength": "0",
                                            "type": "MULTI_SELECT",
                                            "items": repos,
                                        }
                                    },
                                    # {
                                    #     "selectionInput": {
                                    #         "name": "interval",
                                    #         "label": "I would like to check for new updates every:",
                                    #         "type": "RADIO_BUTTON",
                                    #         "items": [
                                    #             {
                                    #                 "text": "5 minutes",
                                    #                 "value": "5m",
                                    #                 "selected": False,
                                    #             },
                                    #             {
                                    #                 "text": "30 minutes",
                                    #                 "value": "30m",
                                    #                 "selected": False,
                                    #             },
                                    #             {
                                    #                 "text": "1 hour",
                                    #                 "value": "1hr",
                                    #                 "selected": False,
                                    #             },
                                    #             {
                                    #                 "text": "8 hours",
                                    #                 "value": "8hr",
                                    #                 "selected": False,
                                    #             },
                                    #             {
                                    #                 "text": "24 hours",
                                    #                 "value": "24hr",
                                    #                 "selected": False,
                                    #             },
                                    #         ],
                                    #     }
                                    # },
                                    {
                                        "buttonList": {
                                            "buttons": [
                                                {
                                                    "text": "Subscribe",
                                                    "onClick": {
                                                        "action": {
                                                            "function": os.environ.get(
                                                                "BASE_URL"
                                                            ),
                                                            "parameters": [
                                                                {
                                                                    "key": "actionName",
                                                                    "value": "submitDialog",
                                                                }
                                                            ],
                                                        }
                                                    },
                                                }
                                            ]
                                        }
                                    },
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    }


def send_chat_message(space_id, message):
    try:
        response = chat_client.create_message(
            request=google_chat.CreateMessageRequest(
                parent=space_id,
                message=message,
            )
        )
        print(f"Response from sending chat message: {response}")

    except Exception as e:
        print(f"Error sending message to space {space_id}: {e}")


categories = [
    "All Blogs",
    "AI & Machine Learning",
    "API Management",
    "Application Development",
    "Application Modernization",
    "Chrome Enterprise",
    "Compute",
    "Containers & Kubernetes",
    "Data Analytics",
    "Databases",
    "DevOps & SRE",
    "Financial Services",
    "Healthcare & Life Sciences",
    "Manufacturing",
    "Media & Entertainment",
    "Public Sector",
    "Retail",
    "Supply Chain & Logistics",
    "Telecommunications",
    "Partners",
    "Startups & SMB",
    "Inside Google Cloud",
    "Google Cloud Consulting",
    # "Maps & Geospatial", # RSS for this category is not available
    "Security & Identity",
    "Threat Intelligence",
    "Infrastructure",
    "Infrastructure Modernization",
    "Networking",
    "Productivity & Collaboration",
    "SAP on Google Cloud",
    "Storage & Data Transfer",
    "Sustainability",
]

channels = [
    "All YouTube Channels",
    "Google Cloud",
    "Google Cloud Tech",
    "Google Cloud Events",
]

repos = [
    "All Repos",
    "adk-python",
    "adk-java",
    "professional-services-data-validator",
    "python-bigquery",
    "java-bigquery",
    "spanner-migration-tool",
]

data_categories = [
    "All Data Blogs",
    "Data Analytics",
    "Databases",
    "SAP on Google Cloud",
    "Storage & Data Transfer",
]

google_cloud_products = [
    "All AI Products",
    "All App Mod Products",
    "All Data Products",
    "All Products",
    "All Security Products",
    "Access Approval",
    "Access Approval v1",
    "Access Context Manager",
    "Access Transparency",
    "Acquirer switch",
    "Advisory Notifications",
    "Agent Assist",
    "Agent Platform Workbench",
    "Agent Platform Workbench v1",
    "Agent Platform Workbench v2",
    "Agent Registry",
    "AI Hub",
    "AI Hypercomputer",
    "AI Platform",
    "AI Platform Data Labeling Service",
    "AI Platform Optimizer",
    "AI Platform Pipelines",
    "AI Platform Prediction",
    "AI Platform Training",
    "AlloyDB for PostgreSQL",
    "AlloyDB Omni",
    "Anthos Attached Clusters",
    "Anthos clusters on AWS",
    "Anthos clusters on AWS (previous generation)",
    "Anthos clusters on Azure",
    "Anthos Config Management",
    "Anthos Service Mesh - Security Bulletins",
    "Anti Money Laundering AI",
    "API Gateway",
    "API Gateway v1",
    "API Keys API",
    "Apigee",
    "Apigee - Security Bulletins",
    "Apigee Adapter for Envoy",
    "Apigee Advanced API Security",
    "Apigee Analytics",
    "Apigee API hub",
    "Apigee Connectors",
    "Apigee hybrid",
    "Apigee Integrated Portal",
    "Apigee Integration",
    "Apigee Monetization",
    "Apigee Operator for kubernetes",
    "Apigee Registry",
    "Apigee UI",
    "Apigee X",
    "App Engine Admin API",
    "App Engine flexible environment .NET",
    "App Engine flexible environment custom runtimes",
    "App Engine flexible environment Go",
    "App Engine flexible environment Java",
    "App Engine flexible environment Node.js",
    "App Engine flexible environment PHP",
    "App Engine flexible environment Python",
    "App Engine flexible environment Ruby",
    "App Engine Standard 1.11",
    "App Engine standard environment Go",
    "App Engine standard environment Go 1.12",
    "App Engine standard environment Go 1.12+",
    "App Engine standard environment Java",
    "App Engine standard environment Java 8",
    "App Engine standard environment Java gen2",
    "App Engine standard environment Node.js",
    "App Engine standard environment PHP",
    "App Engine standard environment PHP 5",
    "App Engine standard environment PHP 7",
    "App Engine standard environment PHP 7+",
    "App Engine standard environment Python",
    "App Engine standard environment Python 2.7",
    "App Engine standard environment Python 3",
    "App Engine standard environment Ruby",
    "App Hub",
    "App Optimize API",
    "Application Design Center",
    "Application Integration",
    "Artifact Registry",
    "Artifact Registry v1",
    "Assured Open Source Software",
    "Assured Workloads",
    "Assured Workloads v1",
    "Assured Workloads v1beta1",
    "Audit Manager",
    "AutoML Natural Language",
    "AutoML Tables",
    "AutoML Translation",
    "AutoML Vision Image Classification (ICN",
    "AutoML Vision Object Detection",
    "Backup and DR",
    "Backup for GKE",
    "Bare Metal Solution",
    "Bare Metal Solution - Security Bulletins",
    "Batch",
    "BeyondCorp Enterprise",
    "BigQuery",
    "BigQuery Engine for Apache Flink",
    "BigQuery ML",
    "Bigtable",
    "Binary Authorization",
    "Blockchain Analytics",
    "Blockchain Node Engine",
    "Buildpacks",
    "Capacity Planner",
    "Carbon Footprint",
    "Certificate Authority Service",
    "Certificate Authority Service v1",
    "Certificate Manager",
    "Channel Services",
    "Channel Services v1",
    "Chrome Enterprise Premium",
    "Cloud API Registry",
    "Cloud Asset Inventory",
    "Cloud Billing",
    "Cloud Build",
    "Cloud CDN",
    "Cloud Composer",
    "Cloud Console",
    "Cloud Data Fusion",
    "Cloud Database Migration Service",
    "Cloud Database Migration Service v1",
    "Cloud Debugger",
    "Cloud Deploy",
    "Cloud Deployment Manager",
    "Cloud DNS",
    "Cloud Domains",
    "Cloud Endpoints",
    "Cloud Healthcare API",
    "Cloud Healthcare API v1",
    "Cloud Healthcare API v1beta1",
    "Cloud Hub",
    "Cloud IAM - Permissions Change Log",
    "Cloud Identity",
    "Cloud IDS",
    "Cloud Interconnect",
    "Cloud Key Management Service",
    "Cloud Life Sciences",
    "Cloud Load Balancing",
    "Cloud Location Finder",
    "Cloud Logging",
    "Cloud Monitoring",
    "Cloud NAT",
    "Cloud Natural Language API",
    "Cloud NGFW",
    "Cloud NGFW v1",
    "Cloud Number Registry",
    "Cloud Optimization AI",
    "Cloud Product Registry API",
    "Cloud Profiler",
    "Cloud Quotas",
    "Cloud Quotas v1",
    "Cloud Quotas v1beta",
    "Cloud Router",
    "Cloud Run",
    "Cloud Run functions",
    "Cloud Scheduler",
    "Cloud SDK",
    "Cloud Secure Web Gateway",
    "Cloud Service Mesh",
    "Cloud Service Mesh - Security Bulletins",
    "Cloud Shell",
    "Cloud Source Repositories",
    "Cloud SQL",
    "Cloud SQL for MySQL",
    "Cloud SQL for PostgreSQL",
    "Cloud SQL for SQL Server",
    "Cloud Storage",
    "Cloud Talent Solution Job Search",
    "Cloud Talent Solution Job Search v4",
    "Cloud Tasks",
    "Cloud Tasks v2",
    "Cloud Tasks v2beta3",
    "Cloud TPU",
    "Cloud Trace",
    "Cloud Translation",
    "Cloud Vision",
    "Cloud Vision API Product Search",
    "Cloud VPN",
    "Cloud Workstations",
    "Cluster Director",
    "Cluster Services for OpenShift",
    "Cluster Toolkit",
    "Colab Enterprise",
    "compute - Security Bulletins",
    "Compute Engine",
    "Compute Engine - Security Bulletins",
    "Confidential Space",
    "Confidential VM",
    "Confidential VM - Security Bulletins",
    "Config Connector",
    "Config Controller",
    "Config Sync",
    "Connect for Anthos",
    "Contact Center AI Insights",
    "Container Optimized OS",
    "Container Registry",
    "Cortex Framework",
    "CX Agent Studio",
    "Data Catalog",
    "Data Catalog v1",
    "Data Catalog v1beta1",
    "Data Studio",
    "Data Transfer Essentials",
    "Database Center",
    "Dataflow",
    "Dataflow - Security Bulletins",
    "Dataform",
    "Dataplex",
    "Dataprep by Trifacta",
    "Dataproc",
    "Dataproc Metastore",
    "Dataproc Serverless",
    "Datastream",
    "Deep Learning Containers",
    "Deep Learning VM Images",
    "Developer Connect",
    "Dialogflow",
    "Discovery Engine API",
    "Document AI",
    "Document AI Warehouse",
    "Endpoint Verification",
    "Enterprise Knowledge Graph",
    "Error Reporting",
    "Eventarc",
    "Filestore",
    "Firestore",
    "Firestore in Datastore mode",
    "Firestore with MongoDB compatibility",
    "Game Servers",
    "Gemini",
    "Gemini Cloud Assist",
    "Gemini Code Assist",
    "Gemini Code Assist in Apigee",
    "Gemini Code Assist VERSION_UNSPECIFIED",
    "Gemini Enterprise",
    "Gemini Enterprise Agent Platform",
    "Gemini on GDC API on GDC connected",
    "Gemini VERSION_UNSPECIFIED",
    "Generative AI on Vertex AI",
    "GitLab on Google Cloud",
    "GKE - Security Bulletins",
    "GKE Enterprise",
    "Google Agentspace",
    "Google Cloud - Security Bulletins",
    "Google Cloud Architecture Center",
    "Google Cloud Armor",
    "Google Cloud Contact Center as a Service",
    "Google Cloud Managed Service for Apache Kafka",
    "Google Cloud Marketplace",
    "Google Cloud Marketplace Partners",
    "Google Cloud MCP servers",
    "Google Cloud Observability",
    "Google Cloud Platform (GCP)",
    "Google Cloud VMware Engine",
    "Google Cloud VMware Engine - Security Bulletins",
    "Google Distributed Cloud (software only) for bare metal",
    "Google Distributed Cloud (software only) for VMware",
    "Google Distributed Cloud connected",
    "Google Distributed Cloud connected - Security Bulletins",
    "Google Distributed Cloud Edge Distributed Cloud Edge management software",
    "Google Kubernetes Engine",
    "Google Kubernetes Engine Extended Channel",
    "Google Kubernetes Engine Main",
    "Google Kubernetes Engine New Features",
    "Google Kubernetes Engine No Channel",
    "Google Kubernetes Engine Rapid Channel",
    "Google Kubernetes Engine Regular Channel",
    "Google Kubernetes Engine Stable Channel",
    "Google SecOps",
    "Google SecOps Marketplace",
    "Google SecOps SIEM",
    "Google SecOps SOAR",
    "Google Threat Intelligence",
    "Guest Environment",
    "Identity and Access Management",
    "Identity Platform",
    "Identity-Aware Proxy",
    "Immersive Stream for XR",
    "Infrastructure Manager",
    "Integration Connectors",
    "IoT Core",
    "Issuer switch",
    "Istio on Google Kubernetes Engine",
    "Key Access Justifications",
    "Kf",
    "Knative serving",
    "Knowledge Catalog",
    "Live Stream API",
    "Looker",
    "Looker Looker (Google Cloud core) and Looker (original) changes",
    "Looker Looker (Google Cloud core) only changes",
    "Looker Looker (original) only changes",
    "Looker Studio",
    "Mainframe Assessment Tool",
    "Mainframe Connector",
    "Mainframe Connector VERSION_UNSPECIFIED",
    "Managed Anthos Service Mesh Managed Anthos Service Mesh",
    "Managed Cloud Service Mesh Managed Cloud Service Mesh",
    "Managed Service for Apache Airflow",
    "Managed Service for Apache Spark",
    "Managed Service for Microsoft Active Directory",
    "Manufacturing Data Engine",
    "Media CDN",
    "Media Translation",
    "Memorystore for Memcached",
    "Memorystore for Memcached v1",
    "Memorystore for Redis",
    "Memorystore for Redis Cluster",
    "Memorystore for Valkey",
    "Migrate to Containers",
    "Migrate to Containers - Security Bulletins",
    "Migrate to Virtual Machines",
    "Migrate to Virtual Machines - Security Bulletins",
    "Migration Center",
    "Model Armor",
    "NetApp Cloud Volumes Service",
    "NetApp Volumes",
    "Network Connectivity Center",
    "Network Intelligence Center",
    "Network Security Integration",
    "Network Service Tiers",
    "Oracle Database@Google Cloud",
    "Oracle on Google Cloud Compute",
    "Organization Policy",
    "Parallelstore",
    "Policy Controller",
    "Policy Intelligence",
    "Pub/Sub",
    "Pub/Sub Lite",
    "reCAPTCHA",
    "Recommendations",
    "Recommender",
    "Recommender v1beta1",
    "Resource Manager",
    "Retail API",
    "Risk Manager",
    "SaaS Runtime",
    "SAP on Google Cloud",
    "Secret Manager",
    "Secure Source Manager",
    "Secure Web Proxy",
    "Security Command Center",
    "Sensitive Data Protection",
    "Service Catalog",
    "Service Catalog v1.1",
    "Service Directory",
    "Service Extensions",
    "Service Health",
    "Service Infrastructure",
    "Service Usage",
    "Sovereign Controls by Partners",
    "Sovereign Controls by Partners for Partners",
    "Spanner",
    "Speech-to-Text",
    "Storage Transfer Service",
    "StratoZone",
    "Telecom Subscriber Insights",
    "Tensorflow Enterprise",
    "Terraform on Google Cloud",
    "Terraform on Google Cloud VERSION_UNSPECIFIED",
    "Text-to-Speech",
    "Tools for PowerShell",
    "Tools for Visual Studio",
    "Traffic Director",
    "Transcoder API",
    "Transfer Appliance",
    "Translation Hub",
    "Unified Maintenance",
    "Vertex AI",
    "Vertex AI Agent Builder",
    "Vertex AI Model Garden",
    "Vertex AI Search",
    "Vertex AI Vision",
    "Vertex AI Workbench",
    "Vertex AI Workbench v1",
    "Vertex AI Workbench v2",
    "Video Intelligence API",
    "Video Stitcher API",
    "Virtual Private Cloud",
    "VM Runtime on Google Distributed Cloud",
    "VPC Service Controls",
    "Web Risk",
    "Workflows",
    "Workflows v1",
]
google_cloud_ai_products = [
    "All AI Products",
    "Agent Assist",
    "Agent Platform Workbench",
    "Agent Platform Workbench v1",
    "Agent Platform Workbench v2",
    "AI Hub",
    "AI Hypercomputer",
    "AI Platform",  # Note: Vertex AI is the successor, but listed separately
    "AI Platform Data Labeling Service",
    "AI Platform Optimizer",
    "AI Platform Pipelines",
    "AI Platform Prediction",
    "AI Platform Training",
    "Anti Money Laundering AI",
    "AutoML Natural Language",
    "AutoML Tables",
    "AutoML Translation",
    "AutoML Vision Image Classification (ICN",
    "AutoML Vision Image Classification (ICN)",
    "AutoML Vision Object Detection",
    "Cloud Healthcare API",
    "Cloud Healthcare API v1",
    "Cloud Healthcare API v1beta1",
    "Cloud Life Sciences",  # Processes data often using AI/ML pipelines
    "Cloud Natural Language API",
    "Cloud Optimization AI",
    "Cloud Talent Solution Job Search",
    "Cloud Talent Solution Job Search v4",
    "Cloud TPU",
    "Cloud Translation",
    "Cloud Vision",
    "Cloud Vision API Product Search",
    "Colab Enterprise",
    "Contact Center AI Insights",
    "CX Agent Studio",
    "Deep Learning Containers",
    "Deep Learning VM Images",
    "Dialogflow",
    "Document AI",
    "Document AI Warehouse",
    "Gemini",
    "Gemini Cloud Assist",
    "Gemini Code Assist",
    "Gemini Code Assist in Apigee",
    "Gemini Code Assist VERSION_UNSPECIFIED",
    "Gemini Enterprise",
    "Gemini Enterprise Agent Platform",
    "Gemini on GDC API on GDC connected",
    "Gemini VERSION_UNSPECIFIED",
    "Generative AI on Vertex AI",
    "Google Agentspace",
    "Google Cloud Contact Center as a Service",  # Often includes CCAI
    "Managed Service for Apache Airflow",
    "Media Translation",
    "Model Armor",
    "Retail API",
    "Speech-to-Text",
    "Tensorflow Enterprise",
    "Text-to-Speech",
    "Translation Hub",
    "Vertex AI",
    "Vertex AI Agent Builder",
    "Vertex AI Model Garden",
    "Vertex AI Search",
    "Vertex AI Vision",
    "Vertex AI Workbench",
    "Vertex AI Workbench v1",
    "Vertex AI Workbench v2",
]

# Application Modernization and General Compute Products
google_cloud_app_mod_products = [
    "All App Mod Products",
    "Anthos Attached Clusters",
    "Anthos clusters on AWS",
    "Anthos clusters on AWS (previous generation)",
    "Anthos clusters on Azure",
    "Anthos Config Management",
    "API Gateway",
    "API Gateway v1",
    "API Keys API",
    "Apigee",
    "Apigee Adapter for Envoy",
    "Apigee Advanced API Security",  # Part of Apigee Suite
    "Apigee Analytics",
    "Apigee API hub",
    "Apigee Connectors",
    "Apigee hybrid",
    "Apigee Integrated Portal",
    "Apigee Integration",
    "Apigee Monetization",
    "Apigee Operator for kubernetes",
    "Apigee Registry",
    "Apigee UI",
    "Apigee X",
    "App Engine Admin API",
    "App Engine flexible environment .NET",
    "App Engine flexible environment custom runtimes",
    "App Engine flexible environment Go",
    "App Engine flexible environment Java",
    "App Engine flexible environment Node.js",
    "App Engine flexible environment PHP",
    "App Engine flexible environment Python",
    "App Engine flexible environment Ruby",
    "App Engine Standard 1.11",
    "App Engine standard environment Go",
    "App Engine standard environment Go 1.12",
    "App Engine standard environment Go 1.12+",
    "App Engine standard environment Java",
    "App Engine standard environment Java 8",
    "App Engine standard environment Java gen2",
    "App Engine standard environment Node.js",
    "App Engine standard environment PHP",
    "App Engine standard environment PHP 5",
    "App Engine standard environment PHP 7",
    "App Engine standard environment PHP 7+",
    "App Engine standard environment Python",
    "App Engine standard environment Python 2.7",
    "App Engine standard environment Python 3",
    "App Engine standard environment Ruby",
    "App Hub",
    "Application Integration",
    "Artifact Registry",
    "Artifact Registry v1",
    "Backup and DR",  # Infrastructure resilience/Ops
    "Backup for GKE",
    "Bare Metal Solution",
    "Batch",
    "Blockchain Node Engine",
    "Buildpacks",
    "Capacity Planner",
    "Cloud Build",
    "Cloud CDN",
    "Cloud Deploy",
    "Cloud DNS",
    "Cloud Domains",
    "Cloud Endpoints",
    "Cloud Interconnect",
    "Cloud Load Balancing",
    "Cloud Logging",  # Ops/Observability aspect
    "Cloud Monitoring",  # Ops/Observability aspect
    "Cloud NAT",
    "Cloud Quotas",  # Ops aspect
    "Cloud Quotas v1",
    "Cloud Quotas v1beta",
    "Cloud Router",
    "Cloud Run",
    "Cloud Run functions",
    "Cloud Service Mesh",
    "Cloud Shell",
    "Cloud Source Repositories",
    "Cloud Tasks",
    "Cloud Tasks v2",
    "Cloud Tasks v2beta3",
    "Cloud Trace",  # Ops/Observability aspect
    "Cloud Workstations",
    "Cluster Director",
    "Cluster Services for OpenShift",
    "Cluster Toolkit",
    "Compute Engine",
    "Config Connector",
    "Config Controller",
    "Connect for Anthos",
    "Container Optimized OS",
    "Container Registry",
    "Developer Connect",
    "Error Reporting",  # Ops/Observability aspect
    "Eventarc",
    "Game Servers",
    "GitLab on Google Cloud",
    "GKE Enterprise",
    "Google Cloud Observability",  # Suite term
    "Google Cloud VMware Engine",
    "Google Distributed Cloud (software only) for bare metal",
    "Google Distributed Cloud (software only) for VMware",
    "Google Distributed Cloud connected",
    "Google Distributed Cloud Edge Distributed Cloud Edge management software",
    "Google Kubernetes Engine",
    "Google Kubernetes Engine Extended Channel",
    "Google Kubernetes Engine Main",
    "Google Kubernetes Engine New Features",
    "Google Kubernetes Engine No Channel",
    "Google Kubernetes Engine Rapid Channel",
    "Google Kubernetes Engine Regular Channel",
    "Google Kubernetes Engine Stable Channel",
    "Immersive Stream for XR",
    "Infrastructure Manager",
    "Integration Connectors",
    "Istio on Google Kubernetes Engine",
    "Kf",
    "Knative serving",
    "Live Stream API",
    "Managed Anthos Service Mesh Managed Anthos Service Mesh",  # Refers to managed service mesh
    "Managed Cloud Service Mesh Managed Cloud Service Mesh",  # Refers to managed service mesh
    "Media CDN",
    "Migrate to Containers",
    "Migrate to Virtual Machines",
    "Migration Center",
    "NetApp Cloud Volumes Service",
    "NetApp Volumes",
    "Network Connectivity Center",
    "Network Intelligence Center",  # Network Ops aspect
    "Recommender",  # Performance/Ops aspect
    "Recommender v1beta1",  # Performance/Ops aspect
    "SAP on Google Cloud",  # Solutions often involve compute/infra
    "Service Catalog",
    "Service Extensions",
    "StratoZone",
    "Terraform on Google Cloud",  # IaC/Ops
    "Transcoder API",
    "Video Stitcher API",
    "Virtual Private Cloud",
    "VM Runtime on Google Distributed Cloud",
    "Workflows",
    "Workflows v1",
]

# Security Products
google_cloud_security_products = [
    "All Security Products",
    "Access Approval",
    "Access Approval v1",
    "Access Context Manager",
    "Access Transparency",
    "Advisory Notifications",  # Includes security advisories
    "Anthos Service Mesh - Security Bulletins",
    "Apigee - Security Bulletins",
    "Assured Open Source Software",
    "Assured Workloads",
    "Assured Workloads v1",
    "Assured Workloads v1beta1",
    "Audit Manager",
    "Bare Metal Solution - Security Bulletins",
    "BeyondCorp Enterprise",
    "Binary Authorization",
    "Certificate Authority Service",
    "Certificate Authority Service v1",
    "Certificate Manager",
    "Chrome Enterprise Premium",
    "Cloud Asset Inventory",  # Security visibility
    "Cloud IAM - Permissions Change Log",
    "Cloud Identity",
    "Cloud IDS",
    "Cloud Key Management Service",
    "Cloud Logging",  # Security Auditing aspect
    "Cloud NGFW",
    "Cloud NGFW v1",
    "Cloud Secure Web Gateway",
    "Cloud Service Mesh - Security Bulletins",
    "Cloud VPN",
    "compute - Security Bulletins",
    "Compute Engine - Security Bulletins",
    "Confidential Space",
    "Confidential VM",
    "Confidential VM - Security Bulletins",
    "Endpoint Verification",
    "GKE - Security Bulletins",
    "Google Cloud - Security Bulletins",
    "Google Cloud Armor",
    "Google Cloud VMware Engine - Security Bulletins",
    "Google Distributed Cloud connected - Security Bulletins",
    "Google SecOps",
    "Google SecOps SIEM",
    "Google SecOps SOAR",
    "Google Threat Intelligence",
    "Identity and Access Management",
    "Identity Platform",
    "Identity-Aware Proxy",
    "Key Access Justifications",
    "Managed Service for Microsoft Active Directory",  # Identity/Security related
    "Migrate to Containers - Security Bulletins",
    "Migrate to Virtual Machines - Security Bulletins",
    "Network Security Integration",
    "Organization Policy",  # Security controls
    "Policy Controller",
    "Policy Intelligence",
    "reCAPTCHA",
    "Recommender",  # Security aspect
    "Recommender v1beta1",  # Security aspect
    "Resource Manager",  # Org structure/boundary control
    "Risk Manager",
    "Secret Manager",
    "Secure Source Manager",  # Source code security focus
    "Secure Web Proxy",
    "Security Command Center",
    "Sensitive Data Protection",
    "Sovereign Controls by Partners",
    "VPC Service Controls",
    "Web Risk",
]

google_cloud_data_products = [
    "All Data Products",
    "AlloyDB for PostgreSQL",
    "AlloyDB Omni",
    "BigQuery",
    "BigQuery Engine for Apache Flink",
    "BigQuery ML",
    "Bigtable",
    "Blockchain Analytics",
    "Cloud Composer",
    "Cloud Data Fusion",
    "Cloud Database Migration Service",
    "Cloud Database Migration Service v1",
    "Cloud SQL",
    "Cloud SQL for MySQL",
    "Cloud SQL for PostgreSQL",
    "Cloud SQL for SQL Server",
    "Cloud Storage",
    "Data Catalog",
    "Data Catalog v1",
    "Data Catalog v1beta1",
    "Data Studio",
    "Data Transfer Essentials",
    "Database Center",
    "Dataflow",
    "Dataflow - Security Bulletins",
    "Dataform",
    "Dataplex",
    "Dataprep by Trifacta",
    "Dataproc",
    "Dataproc Metastore",
    "Dataproc Serverless",
    "Datastream",
    "Enterprise Knowledge Graph",
    "Filestore",
    "Firestore",
    "Firestore in Datastore mode",
    "Firestore with MongoDB compatibility",
    "Google Cloud Managed Service for Apache Kafka",
    "Looker",
    "Looker Looker (Google Cloud core) and Looker (original) changes",
    "Looker Looker (Google Cloud core) only changes",
    "Looker Looker (original) only changes",
    "Looker Studio",
    "Mainframe Assessment Tool",
    "Mainframe Connector",
    "Mainframe Connector VERSION_UNSPECIFIED",
    "Managed Service for Apache Spark",
    "Manufacturing Data Engine",
    "Memorystore for Memcached",
    "Memorystore for Memcached v1",
    "Memorystore for Redis",
    "Memorystore for Redis Cluster",
    "Memorystore for Valkey",
    "Oracle Database@Google Cloud",
    "Oracle on Google Cloud Compute",
    "Parallelstore",
    "Pub/Sub",
    "Pub/Sub Lite",
    "Spanner",
]
